package com.slashserver.model;

// Generated 05-Dec-2011 23:49:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * PageTemplate generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "page_template", catalog = "slash_server")
public class PageTemplate implements HasId {

	private int id;
	private String name;
	private Set<Page> pages = new HashSet<Page>(0);
	private String content;

	public PageTemplate() {
	}

	public PageTemplate(int id) {
		this.id = id;
	}

	public PageTemplate(int id, String name, Set<Page> pages) {
		this.id = id;
		this.name = name;
		this.pages = pages;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pageTemplate")
	public Set<Page> getPages() {
		return this.pages;
	}

	public void setPages(Set<Page> pages) {
		this.pages = pages;
	}

	@Column(name = "content")
	public String getContent() {
		return content;
	}
	
	public void setContent(String content) {
		this.content = content;
	}
	

}
