package com.slashserver.model;

// Generated 05-Dec-2011 23:49:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * UserData generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "user_data", catalog = "slash_server")
public class UserData implements HasId {

	private int id;
	private User user;
	private PageSnippet pageSnippet;
	private String name;
	private String value;

	public UserData() {
	}

	public UserData(int id, User user, PageSnippet pageSnippet, String name) {
		this.id = id;
		this.user = user;
		this.pageSnippet = pageSnippet;
		this.name = name;
	}

	public UserData(int id, User user, PageSnippet pageSnippet, String name, String value) {
		this.id = id;
		this.user = user;
		this.pageSnippet = pageSnippet;
		this.name = name;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "page_snippet_id", nullable = false)
	public PageSnippet getPageSnippet() {
		return this.pageSnippet;
	}

	public void setPageSnippet(PageSnippet pageSnippet) {
		this.pageSnippet = pageSnippet;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
